version: "3.1"

services:
  # postgres:
  #   container_name: postgres
  #   image: postgres:latest
  #   restart: always
  #   volumes:
  #     - ./peppermint/db:/data/db
  #   environment: 
  #     POSTGRES_USER: peppermint
  #     POSTGRES_PASSWORD: 1234
  #     POSTGRES_DB: peppermint
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data/mysql/:/var/lib/mysql/
    environment:
      TZ: Asia/Shanghai # 指定时区
      MYSQL_ROOT_PASSWORD: "xaA4v8r5LGnbLOXp" # 配置root用户密码
      MYSQL_DATABASE: "cool" # 业务库名
      MYSQL_USER: "cool" # 业务库用户名
      MYSQL_PASSWORD: "xaA4v8r5LGnbLOXp" # 业务库密码

  peppermint:
    container_name: peppermint
    build: ../cusdis-master
    ports:
      - 5001:5001
    restart: on-failure
    depends_on:
      - db
    environment:
      PORT: 5001 ## This should follow your ports above, and the port in your base url 
      DB_USERNAME: "root"
      DB_PASSWORD: "xaA4v8r5LGnbLOXp"
      DB_HOST: "db"
      BASE_URL: "http://localhost:5001"
      DB_TYPE: "mysql"
