version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /data/mysqlOrg/:/var/lib/mysql/
      - ./initdb/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai # 指定时区
      MYSQL_ROOT_PASSWORD: "xaA4v8r5LGnbLOXp" # 配置root用户密码
      MYSQL_DATABASE: "cool" # 业务库名
      MYSQL_USER: "cool" # 业务库用户名
      MYSQL_PASSWORD: "xaA4v8r5LGnbLOXp" # 业务库密码

  adminer:
    image: adminer
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区

  redis:
    image: redis
    # command: --requirepass "xaA4v8r5LGnbLOXp" # redis库密码,不需要密码注释本行
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - ./data/redis/:/data/

  midway:
    build: ../cool-admin-midway
 #   build: https://gitee.com/cool-team-official/cool-admin-midway.git # 替换为自已的git地址,或本地目录地址
    image: gcslaoli/cool-admin-midway-demo # 替换为自己要发布的registry的地址，不发布可不修改
    restart: always
    depends_on:
      - db
      - redis
    environment:
      TZ: Asia/Shanghai # 指定时区
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "cool" # 业务库名
      MYSQL_USER: "cool" # 业务库用户名
      MYSQL_PASSWORD: "xaA4v8r5LGnbLOXp" # 业务库密码
    # volumes:
    #   - /pic/uploads:/app/public/uploads

  vue:
  #  build: https://gitee.com/cool-team-official/cool-admin-vue.git # 替换为自已的git地址,或本地目录地址
    build: ../cool-admin-vue
    image: gcslaoli/cool-admin-vue-demo # 替换为自己要发布的registry的地址，不发布可不修改
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    depends_on:
      - midway
    ports:
      - 10000:80 # 将10000改成需要对外发布的端口
    # volumes:
    #   - /pic/uploads:/app/uploads

  org:
  #  build: https://gitee.com/cool-team-official/cool-admin-vue.git # 替换为自已的git地址,或本地目录地址
  #  build: /Users/shuyongduan/01-startup/33-nestJs/06.jingwai/orgloom/orghub-vue-3
    build: ../orghub-vue-3
    image: gcslaoli/orghub-vue-4-demo # 替换为自己要发布的registry的地址，不发布可不修改
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    depends_on:
      - midway
    ports:
      - 10003:80 # 将10000改成需要对外发布的端口
  
  # cusdis:
  # #  build: https://gitee.com/cool-team-official/cool-admin-vue.git # 替换为自已的git地址,或本地目录地址
  # #  build: /Users/shuyongduan/01-startup/33-nestJs/06.jingwai/orgloom/orghub-vue-3
  #   build: ../cusdis-master
  #   image: gcslaoli/cusdis-master-demo # 替换为自己要发布的registry的地址，不发布可不修改
  #   restart: always
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     TZ: Asia/Shanghai # 指定时区
  #     USERNAME: "admin" 
  #     PASSWORD: "password"
  #     DB_URL: "mysql://root:xaA4v8r5LGnbLOXp@127.0.0.1:3306/cudis"
  #     JWTSECRET: "ofcourseistillloveyou"
  #   ports:
  #     - 10005:3000 # 将10000改成需要对外发布的端口

  # pgsql01:
  #   image: "postgres:13"
  #   volumes:
  #     - "./dataCusdis:/var/lib/postgresql/data"
  #   environment:
  #     - POSTGRES_USER=cusdis
  #     - POSTGRES_DB=cusdis
  #     - POSTGRES_PASSWORD=password
  # cusdis:
  #   build: ../cusdis-master
  #   image: "djyde/cusdis-demo"
  #   ports:
  #     - "3000:3000"
  #   # environment:
  #   #   - USERNAME=admin
  #   #   - PASSWORD=password
  #   #   - JWT_SECRET=ofcourseistillloveyou
  #   #   - NEXTAUTH_URL=http://localhost:3000
  #   #   - DB_TYPE=mysql
  #   #   - DB_URL=postgresql://cusdis:password@pgsql01:5432/cusdis
  #   environment:
  #     # PORT: 5001 ## This should follow your ports above, and the port in your base url 
  #     # DB_USERNAME: "root"
  #     # DB_PASSWORD: "xaA4v8r5LGnbLOXp"
  #     # DB_HOST: "db"
  #     # BASE_URL: "http://localhost:5001"
  #     TZ: Asia/Shanghai # 指定时区
  #     MYSQL_HOST: "db"
  #     MYSQL_PORT: "3306"
  #     MYSQL_DATABASE: "cool" # 业务库名
  #     MYSQL_USER: "cool" # 业务库用户名
  #     MYSQL_PASSWORD: "xaA4v8r5LGnbLOXp" # 业务库密码
  #   depends_on:
  #     - db

